electra:
    load_model: electra_chebi50_v241
resgated:
    load_model: resgated_chebi50_v241
chemlog_peptides:
    type: chemlog_peptides
chemlog_element:
    type: chemlog_element
chemlog_organox:
    type: chemlog_organox
c3p:
    load_model: c3p_with_weights
chebi_lookup:
    type: chebi_lookup